### ISSUE TITLE
Passing parameters to farmware

### ISSUE THREAD

**Issue by jason-v-w** [FarmBot-Labs/FarmBot-Python-Examples#3]
Is it currently possible to write farmware in python such that when that farmware is used in a sequence, parameters can be passed? If not, is this a feature that is under development?

For example, I want to write a piece of farmware where the user can specify the number of rows and columns from within the sequence builder and the farmware can then add plants to the farm designer according to the number of rows and columns specified.

**Comment by gabrielburnworth** [comment]
This feature will be available in FarmBot OS version 6. I've uploaded [a farmware](https://github.com/FarmBot-Labs/plant-grid) that was used to develop the feature. Please note that it will only install on FarmBot OS v6.

**Comment by jason-v-w** [comment]
Any idea when version 6 will be released?

**Comment by gabrielburnworth** [comment]
FarmBot OS v6 has been released.
