### ISSUE TITLE
how to get/generate label when build an RPC command.?

### ISSUE THREAD

**Issue by snzip** [FarmBot-Labs/FarmBot-Python-Examples#4]
https://github.com/FarmBot-Labs/FarmBot-Python-Examples/blob/e8122b061090e6b3708c596dfb2cdfcc1a227cc5/publish_example.py#L15

**Comment by RickCarlino** [comment]
@snzip Any random `string` type is fine. It _should_ be unique, though. Please note that the label going to FarmBot as a request will be the same label that comes back from FarmBot as a response. It is good to keep track of these on the client side so you can know when a command is acknowledged.

I recommend using a [uuid generator library](https://stackoverflow.com/questions/534839/how-to-create-a-guid-uuid-in-python)
