### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by jason-v-w** [FarmBot-Labs/FarmBot-Python-Examples#5]
Is there a way (such as via http) to request data saved on the Raspberry Pi? For example, we want to save sensor readings and camera photos to the Pi via custom farmware and be able to access that data from other machines. Ideally we would not have to communicate directly with the Pi (e.g. ssh, sftp, scp, ftp). It seems that the back end of the web interface must be doing this in order to get the camera shots.

**Comment by gabrielburnworth** [comment]
FarmBot OS automatically uploads any image saved to the `os.environ['IMAGES_DIR']` directory to the web app so that you can access them via http ([`GET /api/images`](https://gist.github.com/RickCarlino/10db2df375d717e9efdd3c2d9d8932af#get-apiimages)).

**Comment by RickCarlino** [comment]
@jvwowd There are also API usage examples (for images and all other resources) available here:

https://gist.github.com/RickCarlino/10db2df375d717e9efdd3c2d9d8932af#get-apiimages

Please raise an issue on the [Web App repo](https://github.com/FarmBot/Farmbot-Web-App) if you have any specific questions about API usage.
